 name: CI

 on:
   push:
     branches: [main]
     tags: ["v*"]
   pull_request:
     branches: [main]

 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
         with:
           python-version: "3.8"
       - name: Install and test
         run: |
           cd shell-mcp
           pip install .
           pip install pytest
           pytest

   publish:
     if: startsWith(github.ref, 'refs/tags/v')
     needs: test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
         with:
           python-version: "3.8"
       - name: Publish package
         run: |
           cd shell-mcp
           pip install build twine
           python -m build
           twine upload --skip-existing dist/*